### ISSUE TITLE
Answer to questions in your README

### ISSUE THREAD

**Issue by CTKnight** [vergilchoi/VisualSignal#1]
Hi Vergilchoi, I saw this project in Jike App.

As mentioned in your README, I found the original video is from [KEN KAWAMOTO](fb.com/ken.kawamoto.167), and you can find more about his works in his fb.

Hope this piece of information could help you.

**Comment by CTKnight** [comment]
And the Android App is available at [Google Play Store](https://play.google.com/store/apps/details?id=com.ken.arsensor&rdid=com.ken.arsensor)

**Comment by vergil-zhao** [comment]
Thank you for giving me the information and I have put them into README.md
