### ISSUE TITLE
Small issues with the project

### ISSUE THREAD

**Issue by narciszait** [vergilchoi/VisualSignal#2]
First of all, thank you for the project. 
I wanted to test it out, but i had to install swiftformat since you use it, but you did not mention that.
Second, meshWithClassification works only on iPhones and iPads that have LiDAR. It will crash on unsupported devices.
A simple
`guard ARWorldTrackingConfiguration.supportsSceneReconstruction(.meshWithClassification)
            else {
                print("meshWithClassification isn't supported here.")
                return
            }`
in viewWillAppear would do the trick and prevent the app from crashing on unsupported devices :)

**Comment by vergil-zhao** [comment]
Thanks for trying this gizmo. 😄 

- I didn't use swiftformat, not sure why it is required for you.
- Advice taken and added the code [3d6dc00](https://github.com/vergilchoi/VisualSignal/commit/3d6dc0060d22e0dab987ae409def1af694d4dff2)

**Comment by narciszait** [comment]
Have a look here :) 

![Screenshot 2022-05-25 at 09 04 01](https://user-images.githubusercontent.com/996142/170200853-f744d749-285f-4d33-ab57-580b0b99a751.png)

**Comment by vergil-zhao** [comment]
I don't even have that section 🤔 
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/4736661/170208268-0d1dab8a-2f55-4e4a-829c-c07d48a8fdbf.png">

**Comment by narciszait** [comment]
very weird. i don't know what to say
